[package]
name = "wp-spotlight"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wp-spotlight"
path = "src/main.rs"

[dependencies]
regex = "1.10.2"
walkdir = "2.4.0"
serde = { version = "1.0", features = ["derive"] }
csv = "1.3.0"
clap = { version = "4.4.11", features = ["derive"] }